language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cppcheck
 
# using a symbolic link to get the "make test" to work as if launched from the root directorys
before_script:
  - mkdir build
  - cd build
  - cmake -DSQLITECPP_RUN_CPPLINT=ON -DSQLITECPP_RUN_CPPCHECK=ON -DSQLITECPP_BUILD_EXAMPLES=ON -DSQLITECPP_BUILD_TESTS=ON ..
  - ln -s ../examples examples

script: make && ctest --output-on-failure

